### ISSUE TITLE
When I try to add both the space ID and dynamic URL IDs, getting error

### ISSUE THREAD

**Issue by qwertyuiop97** [fireattack/tslazer#1]
So i am trying to include both the space ID and the dynamic url so that my file name will have the information of the space, since I noticed that using just the dynamic URL doesn't get those details.

But Im getting this error: 

python3 tslazer.py -c '/Users//python/tslazerfireattack/xck1.txt'  -s ****** -d 'https://prod-fastly-_.....m3u8?type=live'
Traceback (most recent call last):
  File "/Users//python/tslazerfireattack/tslazer.py", line 35, in <module>
    TwitterSpace.TwitterSpace(
  File "/Users//python/tslazerfireattack/TwitterSpace.py", line 376, in __init__
    self.playlist_url, self.chat_token = self.get_playlist(self.media_key)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users//python/tslazerfireattack/TwitterSpace.py", line 52, in get_playlist
    dataRequest.raise_for_status()
  File "/Users//python/tslazerfireattack/.venv/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://twitter.com/i/api/1.1/live_video_stream/status/28_1848641610730684416

when i used the dynamic URL alone, the download worked successfully. Thoughts?

**Comment by fireattack** [comment]
It does not support that for now; I can fix it trivially.
